name: Synchronisation Kevin
on:
  push:
    branches: [BrancheKevin]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to hub
        env:
          HF_TOKEN_KEVIN: ${{secrets.HF_TOKEN_KEVIN}}
        run: |
          cd Code/Gradio
          git init
          git config --global user.name "Kemasu"
          git config --global user.email "kevpostic@gmail.com"
          git config --global init.defaultBranch main
          git branch -m main
          git add .
          git commit -m "Synchronisation Kevin"
          git push --force "https://Kemasu:$HF_TOKEN_KEVIN@huggingface.co/spaces/Kemasu/SAE-GPT2-KEVIN" main
