name: Synchronisation Evan
on:
  push:
    branches: [BrancheEvan]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to hub
        env:
          HF_TOKEN_EVAN: ${{secrets.HF_TOKEN_EVAN}}
        run: |
          cd Code/Gradio
          git init
          git config --global user.name "Evanparis240"
          git config --global user.email "evan.paris240@gmail.com"
          git config --global init.defaultBranch main
          git branch -m main
          git add .
          git commit -m "Synchronisation Evan"
          git push --force "https://Evanparis240:$HF_TOKEN_EVAN@huggingface.co/spaces/Evanparis240/SAE-GPT2-EVAN" main
